### ISSUE TITLE
The SlimScroll directive causes 'Uncaught SyntaxError: Unexpected token import' error in scope of Angular 2 (2.0.1 final)

### ISSUE THREAD

**Issue by spzSource** [jkuri/ng2-slimscroll#13]
Looks like SlimScroll causes the following error when we include such directive inside any NgModule:

```
dom_adapter.js:8 Uncaught SyntaxError: Unexpected token import
```

_Environment:_

package.json
```json
"dependencies": {
   "@angular/common": "2.0.1",
    "@angular/compiler": "2.0.1",
    "@angular/core": "2.0.1",
    "@angular/forms": "2.0.1",
    "@angular/http": "2.0.1",
    "@angular/platform-browser": "2.0.1",
    "@angular/platform-browser-dynamic": "2.0.1",
    "@angular/router": "3.0.1",
    "angular2-moment": "^1.0.0-beta.1",
    "adal-angular": "1.0.11",
    "bootstrap": "3.3.7",
    "core-js": "2.4.1",
    "ng2-slimscroll": "0.6.5",
    "ng2-translate": "2.5.0",
    "normalize.css": "4.1.1",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "~0.6.17"
  },
```

The target NgModule:

```ts
@NgModule({
    declarations: [
        NoTaskRunningComponent,
        SlimScroll
    ],
    imports: [
        SharedAppModule,
        CommonModule,
        RouterModule.forChild(CommonRoutes),
    ]
})
export class CommonCModule {

}
```
I suppose the library is outdated and need to be updated to comply with the latest stable version of Angular 2 (2.0.1).

If any further info required, I will be happy to answer.
Cheers, A

**Comment by onpoc** [comment]
thanks @spzSource i also try to merge with my project but gives error now help me that how can i use process?

**Comment by jkuri** [comment]
It should now work https://github.com/jkuri/ng2-slimscroll/commit/789726a5e62f48ac31ff43dd79419e6bc55ad0d8

**Comment by bevrard** [comment]
Hi,

I still have the problem ("Unexpected token import").  Chrome is pointing the second import line:
```
import { BrowserDomAdapter } from '@angular/platform-browser/src/browser/browser_adapter';
```

Regards,
Benjamin

**Comment by spzSource** [comment]
Yes, as I know currently (in 2.0.0 final version) all */src API is a private and it can't be imported in the user code.

**Comment by bevrard** [comment]
@jkuri Do you know if it could be fix?
