### ISSUE TITLE
Angular cli production build - Supplied parameters do not match any signature of call target (v1.3.1)

### ISSUE THREAD

**Issue by vladmarginean9** [jkuri/ng2-slimscroll#44]
After the 1.3.1 update, I encounter the following error when performing production build:
`ERROR .../node_modules/ng2-slimscroll/src/directives/slimscroll.directive.ngfactory.ts (44,35): Supplied parameters do not match any signature of call target.`

Build command: `ng build --prod --base-href ./`

**Comment by jkuri** [comment]
cannot reproduce with latest `angular-cli`.
checked with `ng build --prod` and `ng build --prod --aot`. 
altought I pushed some changes, can you check with `1.3.2`?

**Comment by vladmarginean9** [comment]
Checked with `angular-cli 1.0.2` and `ng2-slimscroll .1.3.2` and it's still an issue. From what I checked, the issue is related to the addition of `@HostListener` in commit `[c1daef9](https://github.com/jkuri/ng2-slimscroll/commit/c1daef95e3e8cbed5aa7f720d30de2097ac675b5)`.
Manually removing the HostListener from the directive solves the problem.

**Comment by vincent-cm** [comment]
@vladmarginean9 but it lost a resize bug fix if you remove that part

**Comment by vincent-cm** [comment]
#46
